SERVICE_NAME=demo-broken
PHP_CONTAINER_NAME=demo-broken-php-1

.PHONY: _list
_list:
	@echo "Type make then a space then hit tab to see available commands"
shell:
	docker exec -it ${PHP_CONTAINER_NAME} bash
